apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gsrz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/integration1-vptt-tenant/integ-app-jlvk/hacbs-test-project-gsrz@sha256:1957c611fcc77877bf3df717aaed17907329f89e61f049d272738d7d65dcacdf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
