apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gsrz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gsrz
    app.kubernetes.io/part-of: integ-app-jlvk
  name: hacbs-test-project-gsrz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gsrz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gsrz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/integration1-vptt-tenant/integ-app-jlvk/hacbs-test-project-gsrz@sha256:1957c611fcc77877bf3df717aaed17907329f89e61f049d272738d7d65dcacdf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
